name: Repository Cylce 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cycle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        node: [10, 12]
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

 
